#
#     Custom player model mod. Powered by GeckoLib.
#     Copyright (C) 2024  CrystalNeko, HappyRespawnanchor, pertaz(Icon Designer)
#
#     This file is part of Ayame.
#
#     Ayame is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Ayame is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Lesser General Public License for more details.
#
#     You should have received a copy of the GNU Lesser General Public License
#     along with Ayame.  If not, see <https://www.gnu.org/licenses/>.
#
# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.1.0+1.21.1
maven_group=org.ayamemc.ayame
archives_name=ayame
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
# ParchmentMC Version
parchment_minecraft_version=1.21
parchment_version=2024.11.10
# Dependencies
fabric_loader_version=0.16.9
fabric_api_version=0.110.0+1.21.1
neoforge_version=21.1.83
# Libs
# GeckoLib Version
geckolib_version=4.7
# Fabric Mod Menu Version
modmenu_version=11.0.3
# Fabric Too Many Shortcuts Version
tms_version=0.0.5+mc.1.21.1
# PaperDoll Render Version
ayame_paperdoll_version=4.3.1+1.21
