#
#     Custom player model mod. Powered by GeckoLib.
#     Copyright (C) 2024-2025  CrystalNeko, HappyRespawnanchor, pertaz(Icon Designer)
#
#     This file is part of Ayame.
#
#     Ayame is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Lesser General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Ayame is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Lesser General Public License for more details.
#
#     You should have received a copy of the GNU Lesser General Public License
#     along with Ayame.  If not, see <https://www.gnu.org/licenses/>.
#
# Gradle Settings
# Gradle JVM arguments
org.gradle.jvmargs=-Xmx2G
# Enable parallel build
org.gradle.parallel=true
# Mod Properties
# Mod license type
mod_license=LGPL-3.0-or-later
# Mod version
mod_version=0.1.0+1.21.1
# Mod name
mod_name=Ayame
# Mod ID
mod_id=ayame
# Archive name for the build output
mod_archives_name=ayame
# Mod description
mod_description=Custom player model mod. Powered by GeckoLib.
# Maven group ID
mod_maven_group=org.ayamemc.ayame
# Mixin configuration file
mod_mixin_config=ayame.mixins.json
# Mod homepage URL
mod_homepage_url=https://github.com/AyameMC/Ayame
# Mod source repository URL
mod_fabric_sources_url=https://github.com/AyameMC/Ayame
# Mod issue tracker URL
mod_issues_url=https://github.com/AyameMC/Ayame/issues
# Platform Settings
# Mod access widener path
mod_access_widener_path=src/main/resources/ayame.accesswidener
# Supported platforms
enabled_platforms=fabric,neoforge
# Minecraft Properties
# Rhino Version
rhino_version=1.8.0
# Minecraft version
minecraft_version=1.21.1
# Dependencies Versions
# Fabric loader version
fabric_loader_version=0.16.10
# Fabric API version
fabric_api_version=0.114.0+1.21.1
# Fabric Minecraft version range
fabric_minecraft_version_range=>=1.21.1
# NeoForge version
neoforge_version=21.1.93
# NeoForge Minecraft version range
neoforge_minecraft_version_range=[1.21.1,)
# Parchment Minecraft version
parchment_minecraft_version=1.21.1
# Parchment version
parchment_version=2024.11.17
# Library Versions
# GeckoLib version
geckolib_version=4.7.3
# Fabric Mod Menu version
modmenu_version=11.0.3
# Fabric Kotlin language version
fabric_language_kotlin_version=1.13.0+kotlin.2.1.0
# Fabric Too Many Shortcuts version
too_many_shortcuts_version=0.0.6+mc.1.21.1
# PaperDoll Render version
ayame_paperdoll_version=4.3.1+1.21
