modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/AyameMC/Ayame/issues/"

[[mods]]
modId = "ayame"
version = "${version}"
displayName = "Ayame"
displayURL = "https://github.com/AyameMC/Ayame/"
authors = '''
CSneko, HappyRespawnanchor
'''
description =    '''
Custom player model mod. Based on GeckoLib.
'''
#logoFile = ""

[[dependencies.ayame]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ayame]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ayame]]
modId = "geckolib"
type = "required"
versionRange = "[4.5.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ayame]]
modId = "optifine"
type = "incompatible"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "ayame.mixins.json"
