modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues_url}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${mod_homepage_url}"
authors = '''
CSneko, HappyRespawnanchor, pertaz(Icon Designer)
'''
credits = '''
pertaz(Icon Desiger)
'''

description = "${mod_description}"
logoFile = "icon.png"
logoBlur = false
updateJSONURL = "https://updatechecker.ayamemc.org/neoforge/ayame/update.json"
[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "geckolib"
type = "required"
versionRange = "[${geckolib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "optifine"
type = "incompatible"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${mod_mixin_config}"

[[mixins]]
config = "ayame-neoforge.mixins.json"
